#! /bin/bash

usage() {
cat << EOF
Usage: prun mdl ${0##*/} -d DATA_DIR -t DATA_TABLE -a ALIGNER [optional: -p NTHREADS -s ALIGNER_PARAMS -o -n -u]

This script processes sequencing data from ChIP-seq and chromatin accessibility assays from fastq to bigwig.

OPTIONS:
   -d PROJECT_DIR	Path to your project data folder.
      	  		The script will create links to the centrally stored data in that location.

   -t DATA_TABLE 	Path to your data table in comma-separated csv format
   	  	  	Download template here: https://bit.ly/38VOMrc
			Ideally store this file in the location you specified as -d DATA_DIR

   -p NTHREADS   	Number of parallel threads

   -n DRY_RUN		Flag for a dry run, i.e. only print the commands instead of executing.
 
   -o OVERWRITE		none|fastq|bam|bw. Lowest level of files to be overwritten. Default: none.

   -s STAR_PARAMS	Optional: any number of parameters for the STAR aligner (for ChIP-seq) in double quotes.
   	  		Example: -s "--outFilterMultimapNmax 1 --outSAMmultNmax 1"

   -u UNALIGNED		Flag for saving unaligned reads to PROJECT_DIR/bam/log/

   -v VERBOSE		Print verbose info
EOF
}

# parse arguments (more info at https://ndench.github.io/bash/parsing-bash-flags)
dry_run_flag=""
nthreads="--cores 1"
overwrite="none"
write_unaligned=False
star_params=" "
verbose=""
keep_going_flag="-k" # don't abort when one job fails
local=False # Flag for saving files locally on the user's project folder instead of centrally. This option will not be advertised.
while getopts ":d:t:p:s:o:nluv" OPTION; do
	case $OPTION in
		d) project_dir=$(realpath $OPTARG) ;; # full path
		t) data_table=$(realpath $OPTARG) ;;
		p) nthreads="--cores $OPTARG" ;;
		n) nthreads="-n --reason" ;;
		o) overwrite=$OPTARG ;;
		l) local=True ;;
		s) star_params=$OPTARG ;;
		u) write_unaligned=True ;;
		v) verbose="-p" ;;
		?) usage; exit 1 ;;
 	esac
done

# throw error if not all mandatory arguments are passed
if [ -z ${project_dir+x} ] || [ -z ${data_table+x} ]; then
	usage
	exit 1
fi

# determine which files to force run (overwrite)
# the fastq rules are the lowest level rules for all three sources (mpi, geo, encode). all rules depending on those rules will be executed too.
declare -A arr=( ["none"]=""
				 ["fastq"]="--forcerun merge_mpi_fastqs download_geo download_encode_single_end download_encode_paired_end"
				 ["bam"]="--forcerun align"
				 ["bw"]="--forcerun bw" )
force_run=${arr[$overwrite]}

echo "Reading the data table"

# run snakefile
snakemake \
	--snakefile /project/process_seq_data/bin/process_seq_data/Snakefile \
	--config \
	project_dir=$project_dir \
	data_table=$data_table \
	star_params=$star_params \
	write_unaligned=$write_unaligned \
	local=$local \
	$force_run \
	$verbose \
	$keep_going_flag \
	$nthreads

