#! /bin/bash

### This script creates the index for the STAR alignment method.

[[ $# -ne 2 ]] && echo "Usage: prun mdl star_index genome.fasta nthreads" && exit 1

fasta=$1
n=$2
build=$(basename $fasta | cut -f 1 -d '.')
index_dir=/project/MDL_ChIPseq/genome_data/star_index
fasta_dir=/project/MDL_ChIPseq/genome_data/fasta

[[ ! -e $fasta_dir/$build.fa ]] && ln -s $fasta $fasta_dir/$build.fa
fasta=$fasta_dir/$build.fa 

STAR --runMode genomeGenerate \
	 --genomeDir $index_dir/${build} \
	 --genomeFastaFiles $fasta \
	 --runThreadN $n
